# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: repository.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10repository.proto\"`\n\nGetRequest\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t\x12\x0e\n\x06market\x18\x03 \x01(\t\x12\x0c\n\x04side\x18\x04 \x01(\t\x12\x0e\n\x06offset\x18\x05 \x01(\x05\"\x1e\n\tGetReturn\x12\x11\n\tjson_data\x18\x01 \x01(\t\" \n\x0bPostRequest\x12\x11\n\tjson_data\x18\x01 \x01(\t\"\"\n\nPostReturn\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2]\n\nRepository\x12%\n\x08GetTrade\x12\x0b.GetRequest\x1a\n.GetReturn\"\x00\x12(\n\tPostTrade\x12\x0c.PostRequest\x1a\x0b.PostReturn\"\x00\x62\x06proto3')



_GETREQUEST = DESCRIPTOR.message_types_by_name['GetRequest']
_GETRETURN = DESCRIPTOR.message_types_by_name['GetReturn']
_POSTREQUEST = DESCRIPTOR.message_types_by_name['PostRequest']
_POSTRETURN = DESCRIPTOR.message_types_by_name['PostReturn']
GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'repository_pb2'
  # @@protoc_insertion_point(class_scope:GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

GetReturn = _reflection.GeneratedProtocolMessageType('GetReturn', (_message.Message,), {
  'DESCRIPTOR' : _GETRETURN,
  '__module__' : 'repository_pb2'
  # @@protoc_insertion_point(class_scope:GetReturn)
  })
_sym_db.RegisterMessage(GetReturn)

PostRequest = _reflection.GeneratedProtocolMessageType('PostRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSTREQUEST,
  '__module__' : 'repository_pb2'
  # @@protoc_insertion_point(class_scope:PostRequest)
  })
_sym_db.RegisterMessage(PostRequest)

PostReturn = _reflection.GeneratedProtocolMessageType('PostReturn', (_message.Message,), {
  'DESCRIPTOR' : _POSTRETURN,
  '__module__' : 'repository_pb2'
  # @@protoc_insertion_point(class_scope:PostReturn)
  })
_sym_db.RegisterMessage(PostReturn)

_REPOSITORY = DESCRIPTOR.services_by_name['Repository']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETREQUEST._serialized_start=20
  _GETREQUEST._serialized_end=116
  _GETRETURN._serialized_start=118
  _GETRETURN._serialized_end=148
  _POSTREQUEST._serialized_start=150
  _POSTREQUEST._serialized_end=182
  _POSTRETURN._serialized_start=184
  _POSTRETURN._serialized_end=218
  _REPOSITORY._serialized_start=220
  _REPOSITORY._serialized_end=313
# @@protoc_insertion_point(module_scope)
