# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import oms_pb2 as oms__pb2


class OrderManagementSystemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSupportedExchanges = channel.unary_unary(
                '/OrderManagementSystem/GetSupportedExchanges',
                request_serializer=oms__pb2.SupportedExchangesGet.SerializeToString,
                response_deserializer=oms__pb2.SupportedExchangesPost.FromString,
                )
        self.GetSupportedMarkets = channel.unary_unary(
                '/OrderManagementSystem/GetSupportedMarkets',
                request_serializer=oms__pb2.SupportedMarketsGet.SerializeToString,
                response_deserializer=oms__pb2.SupportedMarketsPost.FromString,
                )
        self.PlaceOrder = channel.unary_unary(
                '/OrderManagementSystem/PlaceOrder',
                request_serializer=oms__pb2.PlaceOrderGet.SerializeToString,
                response_deserializer=oms__pb2.PlaceOrderPost.FromString,
                )
        self.CancelOrder = channel.unary_unary(
                '/OrderManagementSystem/CancelOrder',
                request_serializer=oms__pb2.CancelOrderGet.SerializeToString,
                response_deserializer=oms__pb2.CancelOrderPost.FromString,
                )
        self.GetOrderStatus = channel.unary_unary(
                '/OrderManagementSystem/GetOrderStatus',
                request_serializer=oms__pb2.OrderStatusGet.SerializeToString,
                response_deserializer=oms__pb2.OrderStatusPost.FromString,
                )


class OrderManagementSystemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSupportedExchanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedMarkets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderManagementSystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSupportedExchanges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedExchanges,
                    request_deserializer=oms__pb2.SupportedExchangesGet.FromString,
                    response_serializer=oms__pb2.SupportedExchangesPost.SerializeToString,
            ),
            'GetSupportedMarkets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedMarkets,
                    request_deserializer=oms__pb2.SupportedMarketsGet.FromString,
                    response_serializer=oms__pb2.SupportedMarketsPost.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=oms__pb2.PlaceOrderGet.FromString,
                    response_serializer=oms__pb2.PlaceOrderPost.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=oms__pb2.CancelOrderGet.FromString,
                    response_serializer=oms__pb2.CancelOrderPost.SerializeToString,
            ),
            'GetOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatus,
                    request_deserializer=oms__pb2.OrderStatusGet.FromString,
                    response_serializer=oms__pb2.OrderStatusPost.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OrderManagementSystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderManagementSystem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSupportedExchanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrderManagementSystem/GetSupportedExchanges',
            oms__pb2.SupportedExchangesGet.SerializeToString,
            oms__pb2.SupportedExchangesPost.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSupportedMarkets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrderManagementSystem/GetSupportedMarkets',
            oms__pb2.SupportedMarketsGet.SerializeToString,
            oms__pb2.SupportedMarketsPost.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrderManagementSystem/PlaceOrder',
            oms__pb2.PlaceOrderGet.SerializeToString,
            oms__pb2.PlaceOrderPost.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrderManagementSystem/CancelOrder',
            oms__pb2.CancelOrderGet.SerializeToString,
            oms__pb2.CancelOrderPost.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrderManagementSystem/GetOrderStatus',
            oms__pb2.OrderStatusGet.SerializeToString,
            oms__pb2.OrderStatusPost.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
