# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: live_data_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17live_data_service.proto\">\n\x0bOddsApiInfo\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\r\n\x05sport\x18\x02 \x01(\t\x12\x0e\n\x06market\x18\x03 \x01(\t\"\x1c\n\x0c\x46\x65\x65\x64IDReturn\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x1d\n\rFeedIDRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t\"\x1a\n\x07\x43ontext\x12\x0f\n\x07\x43ontext\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x1c\n\x0c\x44\x65leteFeedID\x12\x0c\n\x04uuid\x18\x01 \x01(\t2\xc3\x01\n\x0fLiveDataService\x12\x34\n\x13RegisterOddsApiFeed\x12\x0c.OddsApiInfo\x1a\r.FeedIDReturn\"\x00\x12*\n\x0eGetValueOfFeed\x12\x0e.FeedIDRequest\x1a\x06.Value\"\x00\x12\'\n\x11GetSupportedFeeds\x12\x06.Empty\x1a\x08.Context\"\x00\x12%\n\nDeleteFeed\x12\r.DeleteFeedID\x1a\x06.Empty\"\x00\x62\x06proto3')



_ODDSAPIINFO = DESCRIPTOR.message_types_by_name['OddsApiInfo']
_FEEDIDRETURN = DESCRIPTOR.message_types_by_name['FeedIDReturn']
_FEEDIDREQUEST = DESCRIPTOR.message_types_by_name['FeedIDRequest']
_VALUE = DESCRIPTOR.message_types_by_name['Value']
_CONTEXT = DESCRIPTOR.message_types_by_name['Context']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_DELETEFEEDID = DESCRIPTOR.message_types_by_name['DeleteFeedID']
OddsApiInfo = _reflection.GeneratedProtocolMessageType('OddsApiInfo', (_message.Message,), {
  'DESCRIPTOR' : _ODDSAPIINFO,
  '__module__' : 'live_data_service_pb2'
  # @@protoc_insertion_point(class_scope:OddsApiInfo)
  })
_sym_db.RegisterMessage(OddsApiInfo)

FeedIDReturn = _reflection.GeneratedProtocolMessageType('FeedIDReturn', (_message.Message,), {
  'DESCRIPTOR' : _FEEDIDRETURN,
  '__module__' : 'live_data_service_pb2'
  # @@protoc_insertion_point(class_scope:FeedIDReturn)
  })
_sym_db.RegisterMessage(FeedIDReturn)

FeedIDRequest = _reflection.GeneratedProtocolMessageType('FeedIDRequest', (_message.Message,), {
  'DESCRIPTOR' : _FEEDIDREQUEST,
  '__module__' : 'live_data_service_pb2'
  # @@protoc_insertion_point(class_scope:FeedIDRequest)
  })
_sym_db.RegisterMessage(FeedIDRequest)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'live_data_service_pb2'
  # @@protoc_insertion_point(class_scope:Value)
  })
_sym_db.RegisterMessage(Value)

Context = _reflection.GeneratedProtocolMessageType('Context', (_message.Message,), {
  'DESCRIPTOR' : _CONTEXT,
  '__module__' : 'live_data_service_pb2'
  # @@protoc_insertion_point(class_scope:Context)
  })
_sym_db.RegisterMessage(Context)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'live_data_service_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

DeleteFeedID = _reflection.GeneratedProtocolMessageType('DeleteFeedID', (_message.Message,), {
  'DESCRIPTOR' : _DELETEFEEDID,
  '__module__' : 'live_data_service_pb2'
  # @@protoc_insertion_point(class_scope:DeleteFeedID)
  })
_sym_db.RegisterMessage(DeleteFeedID)

_LIVEDATASERVICE = DESCRIPTOR.services_by_name['LiveDataService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ODDSAPIINFO._serialized_start=27
  _ODDSAPIINFO._serialized_end=89
  _FEEDIDRETURN._serialized_start=91
  _FEEDIDRETURN._serialized_end=119
  _FEEDIDREQUEST._serialized_start=121
  _FEEDIDREQUEST._serialized_end=150
  _VALUE._serialized_start=152
  _VALUE._serialized_end=174
  _CONTEXT._serialized_start=176
  _CONTEXT._serialized_end=202
  _EMPTY._serialized_start=204
  _EMPTY._serialized_end=211
  _DELETEFEEDID._serialized_start=213
  _DELETEFEEDID._serialized_end=241
  _LIVEDATASERVICE._serialized_start=244
  _LIVEDATASERVICE._serialized_end=439
# @@protoc_insertion_point(module_scope)
