"""Create trades model

Revision ID: 1538f21aca4e
Revises: 
Create Date: 2022-06-01 10:36:20.344433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1538f21aca4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('market', sa.String(), nullable=False),
                    sa.Column('side', sa.String(), nullable=False),
                    sa.Column('size', sa.Float(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    # ### end Alembic commands ###
